---
- name: Deploy overcloud
  hosts: kube-all
  gather_facts: no
  tasks:
    - name: Disabling SE linux permanent
      command: sed -i --follow-symlinks s/SELINUX=enforcing/SELINUX=disabled/g /etc/sysconfig/selinux
    - name: Disable subscription
      command: sed -i "s/enabled\=aa/enabled\=0/g" /etc/yum/pluginconf.d/subscription-manager.conf
    - name: Enable local repo
      get_url:
        url: http://registry.mad.lab/local.repo
        dest: /etc/yum.repos.d/local.repo
- name: DEPLOY DOCKER
  hosts: kube-all
  gather_facts: no
  tasks:
    - name: Install Packages
      yum:
        state: present
        name:
          - net-tools
          - tcpdump
          - wget
          - nfs-utils
          - yum-utils
          - tcpdump
          - pyOpenSSL
          - python-jinja2
          - python-requests
          - python-setuptools
          - PyYAML
          - python-ipaddr
          - device-mapper-persistent-data
          - lvm2
    - name: Docker igmp_max_memberships
      command: echo net.ipv4.igmp_max_memberships = 200 > /etc/sysctl.d/99-sysctl.conf
    - name: Add docker repo
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: Install docker 18.06.2.ce
      yum:
        state: present
        name:
          - docker-ce-18.06.2.ce
    - name: Create /etc/docker folder
      file:
        path: /etc/docker
        state: directory
    - name: Create docker.service.d
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
    - name: Get daemon.json
      get_url:
        url: http://registry.mad.lab/kube/daemon.json
        dest: /etc/docker/daemon.json
    - name: Add systemd folder
      command: mkdir -p /etc/systemd/system/docker.service.d
    - name: enable docker service
      command: systemctl enable docker
    - name: start docker service
      command: systemctl start docker
- name: DEPLOY KUBERNETES
  hosts: kb-all
  gather_facts: no
  vars:
    kubernetes_version: "1.15.11" # 1.15.11
  tasks:
    - name: Adding kuber.repo
      get_url:
        url: http://registry.mad.lab/kube/kuber.repo
        dest: /etc/yum.repos.d/kubernetes.repo
    - name: /etc/sysctl.d/k8s.confv6
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: net.bridge.bridge-nf-call-ip6tables = 1
        create: yes
    - name: /etc/sysctl.d/k8s.confv4
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: net.bridge.bridge-nf-call-iptables = 1
    - name: netfiler & swapoff -a
      command: "{{item}}"
      with_items:
        - modprobe br_netfilter
        - swapoff -a
    - name: disable swap fstab
      lineinfile:
        path: /etc/fstab
        regexp: swap
        state: absent
    - sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
    - name: Install Kubernetes Packages
      shell: "yum install -y kubelet-{{kubernetes_version}} kubeadm-{{kubernetes_version}} kubectl-{{kubernetes_version}} --disableexcludes=kubernetes"
    - name: systemctl enable kubelet
      command: systemctl enable --now kubelet
    - name: systemctl start kubelet
      command: systemctl start kubelet
    - name: Allow FW rules
      command: "{{item}}"
      with_items:
        - firewall-cmd --permanent --add-port=6443/tcp
        - firewall-cmd --permanent --add-port=2379-2380/tcp
        - firewall-cmd --permanent --add-port=10250/tcp
        - firewall-cmd --permanent --add-port=10251/tcp
        - firewall-cmd --permanent --add-port=10252/tcp
        - firewall-cmd --permanent --add-port=10255/tcp
        - firewall-cmd --permanent --add-port=30000-32767/tcp
        - firewall-cmd --permanent --add-port=6783/tcp
        - firewall-cmd --permanent --add-port=6783-6784/udp
        - firewall-cmd --permanent --add-port=6783/tcp
        - firewall-cmd --reload
- name: CLUSTER INIT
  hosts: kb-controller
  tasks:
    - name: Download acc-provision
      get_url:
        url: http://registry.mad.lab/kube/acc-provision-4.2.2.1-23.el7.x86_64.rpm
        dest: /root/acc-provision-4.2.2.1-23.el7.x86_64.rpm
    - name: Install Provisioning
      command: yum -y localinstall /root/acc-provision-4.2.2.1-23.el7.x86_64.rpm
    - name: Copy aci-containers-config.yaml
      copy:
        src: /root/kubernetes/aci-containers-config.yaml
        dest: /root/aci-containers-config.yaml
    - name: Provision ACI infra
      command: acc-provision -c /root/aci-containers-config.yaml -o aci-containers.yaml -f kubernetes-1.15 -a -u aibarrio -p ijar2761
    - name: Kubernetes cluster initialization
#      command: "kubeadm init --pod-network-cidr=1.2.192.0/23 --apiserver-advertise-address=1.2.128.11"
#      command: "kubeadm init --pod-network-cidr 1.2.192.0/23 --apiserver-advertise-address 1.2.128.11 --service-cidr 1.2.131.0/24"
      command: "kubeadm init --pod-network-cidr 1.2.192.0/23 --apiserver-advertise-address 1.2.128.11 --service-cidr 1.2.131.0/24 --ignore-preflight-errors=CRI"
    - name: Variables entorno
      command: "{{item}}"
      with_items:
        - mkdir -p /root/.kube
        - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        - chown 0:0 /root/.kube/config
#        - kubectl taint nodes --all node-role.kubernetes.io/master-
    - name: Get token
      shell: kubeadm token create --print-join-command
      register: kubeadm_token
    - debug: msg="{{ kubeadm_token.stdout }}"
- name: DEPLOY CISCO CNI
  hosts: kb-controller
  gather_facts: no
  tasks:
    - pause:
      minutes: 5
    - name: Applying Cisco CNI
      command: kubectl apply -f aci-containers.yaml
    - name: Copy snat.yml
      copy:
        src: /root/kubernetes/snat.yml
        dest: /root/snat.yml
    - name: Applying Snat
      command: kubectl apply -f snat.yml
- name: GET SOME DEPLOYMENTS
  hosts: kb-controller
  gather_facts: no
  tasks:
    - name: Centos deployment
      get_url:
        url: http://registry.mad.lab/kube/deployment-centos.yml
        dest: /root/deployment-centos.yml
