---
- name: DEPLOY KUBERNETES
  hosts: kube-master
  gather_facts: no
  vars:
    kubernetes_version: "1.15.11" # 1.15.11
  tasks:
    - name: Adding kuber.repo
      get_url:
        url: http://registry.mad.lab/kube/kuber.repo
        dest: /etc/yum.repos.d/kubernetes.repo
    - name: /etc/sysctl.d/k8s.confv6
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: net.bridge.bridge-nf-call-ip6tables = 1
        create: yes
    - name: /etc/sysctl.d/k8s.confv4
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: net.bridge.bridge-nf-call-iptables = 1
    - name: netfiler & swapoff -a
      command: "{{item}}"
      with_items:
        - modprobe br_netfilter
        - swapoff -a
    - name: disable swap fstab
      lineinfile:
        path: /etc/fstab
        regexp: swap
        state: absent
    - sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
    - name: Install Kubernetes Packages
      shell: "yum install -y kubelet-{{kubernetes_version}} kubeadm-{{kubernetes_version}} kubectl-{{kubernetes_version}} --disableexcludes=kubernetes"
    - name: systemctl enable kubelet
      command: systemctl enable --now kubelet
    - name: systemctl start kubelet
      command: systemctl start kubelet
    - name: Allow FW rules
      command: "{{item}}"
      with_items:
        - firewall-cmd --permanent --add-port=6443/tcp
        - firewall-cmd --permanent --add-port=2379-2380/tcp
        - firewall-cmd --permanent --add-port=10250/tcp
        - firewall-cmd --permanent --add-port=10251/tcp
        - firewall-cmd --permanent --add-port=10252/tcp
        - firewall-cmd --permanent --add-port=10255/tcp
        - firewall-cmd --permanent --add-port=30000-32767/tcp
        - firewall-cmd --permanent --add-port=6783/tcp
        - firewall-cmd --permanent --add-port=6783-6784/udp
        - firewall-cmd --permanent --add-port=6783/tcp
        - firewall-cmd --reload
