---
- name: DEPLOY KUBERNETES
  hosts: kube-all
  gather_facts: no
  vars:
    kubernetes_version: "1.15.11" # 1.15.11
  tasks:
    - name: Adding kuber.repo
      get_url:
        url: http://registry.mad.lab/kube/kuber.repo
        dest: /etc/yum.repos.d/kubernetes.repo
    - name: /etc/sysctl.d/k8s.confv6
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: net.bridge.bridge-nf-call-ip6tables = 1
        create: yes
    - name: /etc/sysctl.d/k8s.confv4
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: net.bridge.bridge-nf-call-iptables = 1
    - name: netfiler & swapoff -a
      command: "{{item}}"
      with_items:
        - modprobe br_netfilter
        - swapoff -a
    - name: disable swap fstab
      lineinfile:
        path: /etc/fstab
        regexp: swap
        state: absent
    - sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
    - name: Install Kubernetes Packages
      shell: "yum install -y kubelet-{{kubernetes_version}} kubeadm-{{kubernetes_version}} kubectl-{{kubernetes_version}} --disableexcludes=kubernetes"
    - name: systemctl enable kubelet
      command: systemctl enable --now kubelet
    - name: systemctl start kubelet
      command: systemctl start kubelet
    - name: Change Local repository IP
      command: sed -i "s/83.44.110.199/88.9.34.56/g" /etc/yum.repos.d/local.repo
    - name: Allow FW rules
      command: "{{item}}"
      with_items:
        - firewall-cmd --permanent --add-port=6443/tcp
        - firewall-cmd --permanent --add-port=2379-2380/tcp
        - firewall-cmd --permanent --add-port=10250/tcp
        - firewall-cmd --permanent --add-port=10251/tcp
        - firewall-cmd --permanent --add-port=10252/tcp
        - firewall-cmd --permanent --add-port=10255/tcp
        - firewall-cmd --permanent --add-port=30000-32767/tcp
        - firewall-cmd --permanent --add-port=6783/tcp
        - firewall-cmd --permanent --add-port=6783-6784/udp
        - firewall-cmd --permanent --add-port=6783/tcp
        - firewall-cmd --permanent --add-port=8472/udp
        - firewall-cmd --permanent --zone=public --set-target=ACCEPT
        - firewall-cmd --permanent --set-target=ACCEPT
        - firewall-cmd --reload
- name: CLUSTER INIT
  hosts: kube-master
  tasks:
    - name: Download acc-provision
      get_url:
        url: http://registry.mad.lab/kube/acc-provision-4.2.2.1-23.el7.x86_64.rpm
        dest: /root/acc-provision-4.2.2.1-23.el7.x86_64.rpm
    - name: Install Provisioning
      command: yum -y localinstall /root/acc-provision-4.2.2.1-23.el7.x86_64.rpm
    - name: Copy aci-containers-config.yaml
      copy:
        src: /root/kubernetes2/aci-containers-config.yaml
        dest: /root/aci-containers-config.yaml
    - name: Provision ACI infra
      command: acc-provision -c /root/aci-containers-config.yaml -o aci-containers.yaml -f kubernetes-1.15 -a -u aibarrio -p ijar2761
    - name: Kubernetes cluster initialization
      command: "kubeadm init --pod-network-cidr 1.1.192.0/23 --apiserver-advertise-address 1.1.128.10 --service-cidr 1.1.131.0/24 --ignore-preflight-errors=CRI"
    - name: Variables entorno
      command: "{{item}}"
      with_items:
        - mkdir -p /root/.kube
        - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        - chown 0:0 /root/.kube/config
#        - kubectl taint nodes --all node-role.kubernetes.io/master-
    - name: Get token
      shell: kubeadm token create --print-join-command
      register: kubeadm_token
    - debug: msg="{{ kubeadm_token.stdout }}"
- name: DEPLOY CISCO CNI
  hosts: kube-master
  gather_facts: no
  tasks:
    - pause:
      minutes: 5
    - name: Applying Cisco CNI
      command: kubectl apply -f aci-containers.yaml
    - name: Copy snat.yml
      copy:
        src: /root/kubernetes2/snat.yml
        dest: /root/snat.yml
    - name: Applying Snat
      command: kubectl apply -f snat.yml
- name: GET SOME DEPLOYMENTS
  hosts: kube-master
  gather_facts: no
  tasks:
    - name: Copy aci-containers-config.yaml
      copy:
        src: /root/kubernetes2/deployment-centos.yml
        dest: /root/deployment-centos.yml
