aci_config:
  system_id: aitor2            # Every opflex cluster must have a distinct ID
  #apic-refreshtime: 1200       # Subscrption refresh-interval in seconds; Max=43200
  apic_hosts:                   # List of APIC hosts to connect for APIC API
  - 10.10.10.59
  vmm_domain:                   # Kubernetes container domain configuration
    mcast_fabric: 225.1.3.50
    encap_type: vxlan           # Encap mode: vxlan or vlan
    mcast_range:                # Every opflex VMM must use a distinct range
      start: 225.22.1.1
      end: 225.22.255.255
    nested_inside:              # Include if nested inside a VMM;
                                #   required for CloudFoundry
                                #   supported for Kubernetes
    # type: vmware              # Specify the VMM vendor (supported: vmware)
    # name: myvmware            # Specify the name of the VMM domain

  # The following resources must already exist on the APIC.
  # They are used, but not created, by the provisioning tool.
  aep: aep_aibarrio          # The AEP for ports/VPCs used by this cluster
  vrf:                          # This VRF used to create all kubernetes EPs
    name: VRF 
    tenant: aitor2           # This can be system-id or common
  l3out:
    name: L3OUT-KUBE          # Used to provision external IPs
    external_networks:
    - ANY          # Used for external contracts
  #custom_epgs:                 # List of additional endpoint-group names
  #  - custom_group1            # to configure for use with annotations
  #  - custom_group2
  #isolation_segments:          # List of names of isolation segments
  #  - name: iso-seg-1          # and the subnets to use (CloudFoundry only)
  #    subnet: 10.11.0.1/24
  #  - name: iso-seg-2
  #    subnet: 10.11.1.1/24

#
# Networks used by ACI containers
#
net_config:
  node_subnet: 1.1.128.1/24      # Subnet to use for nodes
  pod_subnet: 1.1.192.1/23    # Subnet to use for Kubernetes
                                #   Pods/CloudFoundry containers
  #vip_subnet: 1.1.0.1/16      # Subnet to use for virtual IPs
                                #   (CloudFoundry only)
  extern_dynamic: 1.1.129.1/24   # Subnet to use for dynamic external IPs
  extern_static: 1.1.130.1/24    # Subnet to use for static external IPs
  node_svc_subnet: 1.1.131.1/24  # Subnet to use for service graph
  kubeapi_vlan: 108            # The VLAN used by the physdom for nodes
                                #   (Kubernetes only)
  service_vlan: 197            # The VLAN used by LoadBalancer services
  infra_vlan: 3967              # The VLAN used by ACI infra
  interface_mtu: 1900          # min = 1280 for ipv6, max = 8900 for VXLAN
  #service_monitor_interval: 5  # IPSLA interval probe time for PBR tracking
                                # default is 0, set to > 0 to enable, max: 65535
  #pbr_tracking_non_snat: true  # Default is false, set to true for IPSLA to
                                # be effective with non-snat services

#
# Configuration for container registry
# Update if a custom container registry has been setup
#
registry:
  image_prefix: noiro                   # e.g: registry.example.com/noiro
  # image_pull_secret: secret_name      # (if needed)

kube_config:
  # ovs_memory_limit: "20Gi"            # override if needed, default is "1Gi"
  # reboot_opflex_with_ovs: "false"     # override if needed, default is "true"
  snat_operator:
    port_range:
      start: 6000
      end: 62000
      ports_per_node: 500
