apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: centos
  namespace: default
  labels:
    app: centos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
      - image: centos
        name: centos
        command: ["/usr/bin/ping","127.0.0.1"]
        imagePullPolicy: IfNotPresent
